user:
  avatar_size: 50
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  users_per_page: 10
post:
  maximun_title: 50
  maximum_content: 1000
  posts_per_page: 10
comment:
  maximum_content: 140
helper:
  avatar_size: 80
