user:
  avatar_size: 50
  avatar_size_follow: 30
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  users_per_page: 10
post:
  maximun_title: 50
  posts_per_page: 10
comment:
  avatar_size: 30
helper:
  avatar_size: 80
